title: PetCarePro
description: "Expert pet care tips, guides, and advice for happy, healthy pets."
url: "https://kkumakkuma.github.io"
baseurl: "/PetCarePro"
permalink: /:year/:month/:day/:title/
future: true

theme: minima

author:
  name: PetCarePro
  email: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

google_analytics: "G-5L40K3SBQT"

exclude:
  - scripts/
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock
